include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - deploy
  - scan

image: docker:latest

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    TAGS: "jitesoft/ansible:latest ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker pull alpine:latest
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -t jitesoft/ansible:latest --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - docker push jitesoft/ansible:latest

scan:
  extends: .container_scanning
